/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.User;

import java.rmi.RemoteException;
import java.util.List;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import service.Session;
import util.RemoteProvider;
import util.Utils;

/**
 *
 * @author llama
 */
public class UserBets extends javax.swing.JFrame {

    private final Session session;
    private DefaultTableModel tableModel = 
            new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {"Id", "Amount", "K", "Event", "Outcome", "Status"}
            ) 
            {
                Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                };
                
                boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
                
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            };
    
    /**
     * Creates new form UserBets
     */
    public UserBets(Session session) {
        initComponents();
        this.session = session;
        Utils.centerFrame(this);
        update();
    }

    public void update(){
        try {
            List<Map<String,Object>> bets = RemoteProvider.getUserService().getBets(session);
            for (Map<String, Object> buf : bets) {
                Object [] row = {
                    buf.get("id"),
                    buf.get("amount"),
                    buf.get("k"),
                    buf.get("event"),
                    buf.get("outcome"),
                    buf.get("status")
                };
                tableModel.addRow(row);
            }
        } catch (RemoteException ex) {
            throw new IllegalStateException("Can not update bet list!",ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        resultTable.setModel(tableModel);
        jScrollPane1.setViewportView(resultTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable resultTable;
    // End of variables declaration//GEN-END:variables
}
